/*
 * generated by Xtext 2.23.0
 */
package fr.unice.polytech.si5.toylanguage.concretesyntax;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ToyRuntimeModule extends AbstractToyRuntimeModule {
}
