/*
 * generated by Xtext 2.23.0
 */
package fr.unice.polytech.si5.toylanguage.concretesyntax;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ToyStandaloneSetup extends ToyStandaloneSetupGenerated {

	public static void doSetup() {
		new ToyStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
