/*
 * generated by Xtext 2.23.0
 */
package fr.unice.polytech.si5.toylanguage.concretesyntax.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ToyUiModule extends AbstractToyUiModule {

	public ToyUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
