/*
 * generated by Xtext 2.23.0
 */
package fr.unice.polytech.si5.toylanguage.concretesyntax.parser.antlr;

import com.google.inject.Inject;
import fr.unice.polytech.si5.toylanguage.concretesyntax.parser.antlr.internal.InternalToyParser;
import fr.unice.polytech.si5.toylanguage.concretesyntax.services.ToyGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ToyParser extends AbstractAntlrParser {

	@Inject
	private ToyGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalToyParser createParser(XtextTokenStream stream) {
		return new InternalToyParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ToyProgram";
	}

	public ToyGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ToyGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
