/*
 * generated by Xtext 2.23.0
 */
package fr.unice.polytech.si5.toylanguage.concretesyntax.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.unice.polytech.si5.toylanguage.concretesyntax.ToyRuntimeModule;
import fr.unice.polytech.si5.toylanguage.concretesyntax.ToyStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ToyIdeSetup extends ToyStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ToyRuntimeModule(), new ToyIdeModule()));
	}
	
}
