/*
 * generated by Xtext 2.23.0
 */
package fr.unice.polytech.si5.toylanguage.concretesyntax.ide;


/**
 * Use this class to register ide components.
 */
public class ToyIdeModule extends AbstractToyIdeModule {
}
